/*
WHERE STATEMENT
=, <>, <, >, AND, OR, LIKE, NULL, NOT NULL, IN
*/

-- FILTRAR VALOR EXATO EM UMA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE FirstName = 'Jim'

-- FILTRAR VALOR DIFERENTE EM UMA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE FirstName <> 'Jim'

-- FILTRAR CORTE PARA UM VALOR NUMERICO MAIOR EM UMA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE Age > 30

-- FILTRAR CORTE PARA UM VALOR NUMERICO MAIOR OU IGUAL EM UMA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE Age >= 30

-- FILTRAR CORTE PARA UM VALOR NUMERICO MENOR OU IGUAL EM UMA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE Age <= 32

-- FILTRAR PARA DUAS VARIAVEIS VALOR NUMERICO MENOR OU IGUAL DE UMA E VALOR EXATO DE OUTRA
SELECT *
FROM EmployeeDemographics
WHERE Age <= 32 AND Gender = 'Male'

-- FILTRAR PARA DUAS VARIAVEIS VALOR NUMERICO MENOR OU IGUAL DE UMA OR VALOR EXATO DE OUTRA
SELECT *
FROM EmployeeDemographics
WHERE Age <= 32 OR Gender = 'Male'


-- FILTRAR PARA VALORES APROXIMADOS - usado mais para texto


-- FILTRAR PARA TEXTOS QUE COMECEM COM A LETRA S
SELECT *
FROM EmployeeDemographics
WHERE LastName LIKE 'S%'

-- FILTRAR PARA TEXTOS QUE COMECEM A LETRA S E TEM A LETRA O MINUSCULA
SELECT *
FROM EmployeeDemographics
WHERE LastName LIKE 'S%o%'


-- FILTRAR PARA TEXTOS QUE COMECEM A LETRA S E TEM A LETRA O MINUSCULA
SELECT *
FROM EmployeeDemographics
WHERE LastName LIKE 'S%o%' -- 'S%c%ott%'

-- FILTRAR PARA VALORES NULOS NA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE FirstName IS NULL

-- FILTRAR PARA VALORES NAO NULOS NA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE FirstName IS NOT NULL


-- FILTRAR PARA MULTIPLAS OBSERVACOES EM UMA VARIAVEL
SELECT *
FROM EmployeeDemographics
WHERE FirstName IN ('Jim','Michael','Pam')